export enum MatchesErrorCode {
  MATCH_NOT_FOUND = 'MATCH_NOT_FOUND',
  MATCH_ALREADY_STARTED = 'MATCH_ALREADY_STARTED',
  MATCH_ALREADY_FINISHED = 'MATCH_ALREADY_FINISHED',
  MATCH_NOT_IN_PROGRESS = 'MATCH_NOT_IN_PROGRESS',
  MATCH_NOT_SCHEDULED = 'MATCH_NOT_SCHEDULED',
  INVALID_POINT_TEAM = 'INVALID_POINT_TEAM',
  SET_NOT_FOUND = 'SET_NOT_FOUND',
  MISSING_OPPONENT = 'MISSING_OPPONENT',
  WALKOVER_TEAM_REQUIRED = 'WALKOVER_TEAM_REQUIRED',
  NOT_MATCH_REFEREE = 'NOT_MATCH_REFEREE',
  PLAYER_NOT_IN_TEAM = 'PLAYER_NOT_IN_TEAM',
  SAME_PLAYER_SUBSTITUTION = 'SAME_PLAYER_SUBSTITUTION',
  SCORE_NOT_WINNING = 'SCORE_NOT_WINNING',
  DUPLICATE_LINEUP_POSITION = 'DUPLICATE_LINEUP_POSITION',
  LINEUP_REQUIRED = 'LINEUP_REQUIRED',
}

export const MatchesErrorMessages: Record<MatchesErrorCode, string> = {
  [MatchesErrorCode.MATCH_NOT_FOUND]: 'Match not found',
  [MatchesErrorCode.MATCH_ALREADY_STARTED]: 'Match has already started',
  [MatchesErrorCode.MATCH_ALREADY_FINISHED]: 'Match has already finished',
  [MatchesErrorCode.MATCH_NOT_IN_PROGRESS]: 'Match is not in progress',
  [MatchesErrorCode.MATCH_NOT_SCHEDULED]: 'Match must be scheduled to perform this action',
  [MatchesErrorCode.INVALID_POINT_TEAM]: 'Point must be scored by team "A" or "B"',
  [MatchesErrorCode.SET_NOT_FOUND]: 'Set not found for this match',
  [MatchesErrorCode.MISSING_OPPONENT]: 'Match requires both teams to start',
  [MatchesErrorCode.WALKOVER_TEAM_REQUIRED]: 'Must specify which team wins the walkover (A or B)',
  [MatchesErrorCode.NOT_MATCH_REFEREE]: 'Only the designated referee can perform this action',
  [MatchesErrorCode.PLAYER_NOT_IN_TEAM]: 'Player is not a member of the specified team',
  [MatchesErrorCode.SAME_PLAYER_SUBSTITUTION]: 'Player in and player out must be different',
  [MatchesErrorCode.SCORE_NOT_WINNING]: 'Score does not meet winning criteria',
  [MatchesErrorCode.DUPLICATE_LINEUP_POSITION]: 'Each court position (1-6) can only be assigned once',
  [MatchesErrorCode.LINEUP_REQUIRED]: 'Both teams must have a full 6-position lineup set for this set before scoring',
};
