/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: "#7C3AED",
          "primary-light": "#8B5CF6",
          "accent-lime": "#C6F82A",
          "purple-deep": "#2D1B69",
          "lime-text": "#12100A",
        },
        dark: {
          base: "#0C0A12",
          card: "#141019",
          elevated: "#171320",
          interactive: "#1C1630",
          frame: "#050409",
          sheet: "#161222",
        },
        light: {
          base: "#F6F4FC",
          card: "#FFFFFF",
          frame: "#ECEAF4",
          interactive: "#F0ECFA",
        },
        "dt": {
          primary: "#F5F3FA",
          secondary: "#CFC8E0",
          tertiary: "#A9A2BC",
          muted: "#948CA8",
          disabled: "#6E6684",
        },
        "lt": {
          primary: "#1A1030",
          secondary: "#4A4460",
          tertiary: "#6B6480",
          muted: "#8A829E",
          disabled: "#A29CB4",
        },
        semantic: {
          success: "#34D399",
          "success-dark": "#059669",
          "success-bg": "#D1FAE5",
          warning: "#FBBF24",
          "warning-dark": "#D97706",
          error: "#EF4444",
          "error-light": "#FF6B79",
          "error-bg": "#FEE2E2",
        },
      },
      fontFamily: {
        "heading": ["SpaceGrotesk_700Bold"],
        "heading-800": ["SpaceGrotesk_700Bold"],
        "heading-600": ["SpaceGrotesk_600SemiBold"],
        "heading-500": ["SpaceGrotesk_500Medium"],
        "body": ["Manrope_400Regular"],
        "body-500": ["Manrope_500Medium"],
        "body-600": ["Manrope_600SemiBold"],
        "body-700": ["Manrope_700Bold"],
        "body-800": ["Manrope_800ExtraBold"],
      },
      spacing: {
        "micro": "2px",
        "xs": "4px",
        "sm": "8px",
        "card-gap": "10px",
        "md": "12px",
        "lg": "16px",
        "xl": "20px",
        "page": "22px",
        "2xl": "24px",
        "cta": "28px",
        "otp-gap": "32px",
      },
      borderRadius: {
        "pill": "6px",
        "badge": "8px",
        "btn-sm": "12px",
        "input": "14px",
        "btn": "16px",
        "card": "18px",
        "card-lg": "22px",
        "sheet": "28px",
        "phone": "46px",
        "toggle": "13px",
        "tab-pill": "11px",
      },
      fontSize: {
        "display": ["36px", { lineHeight: "1.1", letterSpacing: "-0.03em" }],
        "splash": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "h1": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "h2": ["22px", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "h3": ["20px", { lineHeight: "1.3", letterSpacing: "-0.02em" }],
        "h4": ["18px", { lineHeight: "1.3" }],
        "section": ["16px", { lineHeight: "1.3" }],
        "btn-label": ["14px", { lineHeight: "1.3", letterSpacing: "0.03em" }],
        "tab": ["13px", { lineHeight: "1.3" }],
        "btn-sm": ["12px", { lineHeight: "1.3" }],
        "badge": ["10px", { lineHeight: "1.3", letterSpacing: "0.06em" }],
        "card-title": ["15px", { lineHeight: "1.3" }],
        "info-label": ["14px", { lineHeight: "1.3" }],
        "input": ["14px", { lineHeight: "1.3" }],
        "body": ["13.5px", { lineHeight: "1.6" }],
        "list": ["13px", { lineHeight: "1.3" }],
        "subtitle": ["12px", { lineHeight: "1.3" }],
        "caption": ["11px", { lineHeight: "1.3" }],
        "fine": ["11.5px", { lineHeight: "1.5" }],
        "tab-bar": ["10px", { lineHeight: "1.3" }],
        "badge-sm": ["9px", { lineHeight: "1.3", letterSpacing: "0.06em" }],
      },
    },
  },
  plugins: [],
};
